//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetLearning.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contests()
        {
            this.contest_participations = new HashSet<contest_participations>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string food_item { get; set; }
        public string location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contest_participations> contest_participations { get; set; }
    }
}
