//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetLearning.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contest_participations
    {
        public int user_id { get; set; }
        public int contest_id { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> placement { get; set; }
    
        public virtual contests contests { get; set; }
        public virtual users users { get; set; }
    }
}
