INSERT INTO [dbo].[contest_participations] ([user_id], [contest_id], [score], [placement]) VALUES (3, 1, 98, 1)
INSERT INTO [dbo].[contest_participations] ([user_id], [contest_id], [score], [placement]) VALUES (3, 3, 80, 1)
INSERT INTO [dbo].[contest_participations] ([user_id], [contest_id], [score], [placement]) VALUES (3, 4, 76, 2)
INSERT INTO [dbo].[contest_participations] ([user_id], [contest_id], [score], [placement]) VALUES (1, 1, 67, 8)
INSERT INTO [dbo].[contest_participations] ([user_id], [contest_id], [score], [placement]) VALUES (2, 3, 70, 4)
INSERT INTO [dbo].[contest_participations] ([user_id], [contest_id], [score], [placement]) VALUES (2, 1, 1, 15)
